services:
  bot:
    container_name: adrrbot
    image: stanocs5/adrrbot:latest
    restart: unless-stopped
    command: pnpm start:production
    volumes:
      - db-data:/app/prisma
      - ./.env:/app/.env
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=file:/app/prisma/data.db

  watchtower:
    image: containrrr/watchtower
    container_name: adrrbot-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ec2-user/.docker/config.json:/config.json:ro
    env_file:
      - ./.env
    command: --interval 300 --cleanup adrrbot
volumes:
  db-data: