services:
  bot:
    container_name: adrrbot
    image: stanocs5/adrrbot:latest
    build: .
    restart: unless-stopped
    command: pnpm start:production
    volumes:
      - db-data:/app/prisma
      - ./.env:/app/.env
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=file:/app/prisma/data.db

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/root/.docker/config.json
    command: --interval 7200 adrrbot  # Polls every 100 minutes and updates only the 'adrrbot' container

volumes:
  db-data: